const tokenMap = (palette) => ({
  "--dsw-alias-bg-base": palette.base,
  "--dsw-alias-bg-layer-1": palette.mantle,
  "--dsw-alias-bg-layer-2": palette.surface,
  "--dsw-alias-bg-layer-3": palette.overlay,
  "--dsw-alias-bg-overlay": palette.mantle,
  "--dsw-alias-bg-primary": palette.surface,
  "--dsw-alias-bg-module-platform": palette.mantle,
  "--dsw-alias-bg-multi-select": palette.overlay,
  "--dsw-alias-border-l1": palette.surface,
  "--dsw-alias-border-l2": palette.overlay,
  "--dsw-alias-border-l3": palette.muted,
  "--dsw-alias-border-secondary": palette.overlay,
  "--dsw-alias-brand-primary": palette.accent,
  "--dsw-alias-brand-primary-invert": palette.base,
  "--dsw-alias-brand-text": palette.accent,
  "--dsw-alias-button-primary-fill": palette.accent,
  "--dsw-alias-button-primary-hover": palette.accentHover,
  "--dsw-alias-button-primary-dimmed": palette.overlay,
  "--dsw-alias-button-ghost-active-fill": palette.surface,
  "--dsw-alias-button-ghost-active-hover": palette.overlay,
  "--dsw-alias-button-floating-fill": palette.surface,
  "--dsw-alias-button-floating-hover": palette.overlay,
  "--dsw-alias-button-tool-bar-fill": palette.surface,
  "--dsw-alias-button-tool-bar-hover": palette.overlay,
  "--dsw-alias-fill-l2": palette.surface,
  "--dsw-alias-interactive-bg-primary": palette.surface,
  "--dsw-alias-interactive-bg-active": palette.overlay,
  "--dsw-alias-interactive-bg-hover": palette.surface,
  "--dsw-alias-interactive-bg-hover-accent": palette.overlay,
  "--dsw-alias-label-primary": palette.text,
  "--dsw-alias-label-primary-foreground": palette.base,
  "--dsw-alias-label-primary-inverted": palette.base,
  "--dsw-alias-label-secondary": palette.subtext,
  "--dsw-alias-label-tertiary": palette.muted,
  "--dsw-alias-label-quaternary": palette.muted,
  "--dsw-alias-label-caption": palette.subtext,
  "--dsw-alias-label-dimmed": palette.muted,
  "--dsw-alias-label-error": palette.red,
  "--dsw-alias-label-primary-bluish": palette.blue,
  "--dsw-alias-line-secondary": palette.overlay,
  "--dsw-alias-separator-primary": palette.surface,
  "--dsw-alias-markdown-code-block": palette.mantle,
  "--dsw-alias-markdown-code-block-banner": palette.surface,
  "--dsw-alias-markdown-inline-code": palette.surface,
  "--dsw-alias-markdown-citation": palette.accent,
  "--dsw-alias-markdown-tag": palette.blue,
  "--dsw-alias-scrollbar-bg-l1": palette.overlay,
  "--dsw-alias-scrollbar-bg-l2": palette.muted,
  "--dsw-alias-scrollbar-hover-l1": palette.muted,
  "--dsw-alias-scrollbar-hover-l2": palette.subtext,
  "--dsw-alias-state-error-primary": palette.red,
  "--dsw-alias-state-error-secondary": palette.red,
  "--dsw-alias-state-success-primary": palette.green,
  "--dsw-alias-state-success-secondary": palette.green,
  "--dsw-alias-state-warn-label": palette.yellow,
  "--dsw-alias-state-warn-primary": palette.yellow,
  "--dsw-alias-toast-bg": palette.surface,
  "--dsw-alias-tooltip-bg": palette.mantle,
});

const define = (id, label, palette) => Object.freeze({
  id,
  label,
  colorScheme: "dark",
  preview: Object.freeze([palette.base, palette.surface, palette.accent, palette.text]),
  tokens: Object.freeze(tokenMap(palette)),
});

export const themes = Object.freeze([
  define("catppuccin-mocha", "Catppuccin Mocha", {
    base: "#1e1e2e", mantle: "#181825", surface: "#313244", overlay: "#45475a",
    text: "#cdd6f4", subtext: "#bac2de", muted: "#6c7086", accent: "#cba6f7",
    accentHover: "#b4befe", blue: "#89b4fa", red: "#f38ba8", green: "#a6e3a1", yellow: "#f9e2af",
  }),
  define("gruvbox-dark", "Gruvbox Dark", {
    base: "#282828", mantle: "#1d2021", surface: "#3c3836", overlay: "#504945",
    text: "#ebdbb2", subtext: "#d5c4a1", muted: "#a89984", accent: "#fe8019",
    accentHover: "#fabd2f", blue: "#83a598", red: "#fb4934", green: "#b8bb26", yellow: "#fabd2f",
  }),
  define("nord", "Nord", {
    base: "#2e3440", mantle: "#242933", surface: "#3b4252", overlay: "#434c5e",
    text: "#eceff4", subtext: "#d8dee9", muted: "#7b88a1", accent: "#88c0d0",
    accentHover: "#8fbcbb", blue: "#81a1c1", red: "#bf616a", green: "#a3be8c", yellow: "#ebcb8b",
  }),
  define("tokyo-night", "Tokyo Night", {
    base: "#1a1b26", mantle: "#16161e", surface: "#24283b", overlay: "#414868",
    text: "#c0caf5", subtext: "#a9b1d6", muted: "#737aa2", accent: "#7aa2f7",
    accentHover: "#bb9af7", blue: "#7dcfff", red: "#f7768e", green: "#9ece6a", yellow: "#e0af68",
  }),
  define("dracula", "Dracula", {
    base: "#282a36", mantle: "#21222c", surface: "#343746", overlay: "#44475a",
    text: "#f8f8f2", subtext: "#d7d7d2", muted: "#6272a4", accent: "#bd93f9",
    accentHover: "#ff79c6", blue: "#8be9fd", red: "#ff5555", green: "#50fa7b", yellow: "#f1fa8c",
  }),
]);

export const themeIds = Object.freeze(["system", ...themes.map((theme) => theme.id)]);
export const isThemeId = (value) => typeof value === "string" && themeIds.includes(value);
